name: Lint with Pyright

on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.5.2
    - name: Set up Python
      uses: actions/setup-python@v4.5.0
      with:
        python-version: '3.8'
        cache: 'pip'
        cache-dependency-path: 'pyproject.toml'
    - name: Install pyright
      run: pip install pyright
    - name: Install berconpy
      run: pip install .
    - name: Run pyright
      run: pyright
