name: Lint with Pyright

on:
  push:
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.11'
          enable-cache: true
      - run: uv sync --locked --all-extras --dev
      - run: uv pip install pyright
      - run: uv run -m pyright
